### ISSUE TITLE
Libruary link error

### ISSUE THREAD

**Issue by ua0lnj** [Zabrimus/vdr-plugin-hbbtv#1]
Ubuntu 18.04 x64
Compiling the plugin is fine, but then when starting VDR I have:
undefined symbol: nn_connect

Need some changes in Makefile:
Add in line 30:
LDFLAGS = -lnanomsg
And set line 108 to:
$(CXX) $(CXXFLAGS)  -shared $(OBJS) $(LDFLAGS) $(LIBS) -o $@

Then vdr and the plugin work fine.

**Comment by Zabrimus** [comment]
Makefile changed with suggested changes.
