### ISSUE TITLE
Stuck with configuration

### ISSUE THREAD

**Issue by Kitoko86** [Zabrimus/vdr-plugin-hbbtv#7]
HI,

I'm looking for a way to make vdr-plugin-hbbtv working on my Ubuntu 20.04 set-up but I can't. I have already installed vdr-osr-browser however it seems that's not enough. Could you explain the steps to follow?

**Comment by Zabrimus** [comment]
The new encoding-Branch or the older one?
1. install browser
2. install plugin
3. configure plugin to use the browser (see parameters on the main page)

A first try is to start the browser standalone,  to check if the browser starts. 
And then configure VDR.  

Could you please explain, what exactly is not working and if there exists some log entries regarding the browser and the plugin?

**Comment by Kitoko86** [comment]
I use the encoding branch. The issue seems linked to my GPU and the browser. In fact, here is the error message from the debug log:
`WARNING:gpu_process_host.cc(1282)] The GPU process has crashed 1 time(s)`

It repeats 9 times before the browser stops.

I own a MSI laptop with an Intel Core i7 10950H with Intel UHD 630 iGPU and NVIDIA RTX 3060. I use the Optimus application to switch from one GPU to the other. Even disabling the RTX, the problem remains. Intel drivers to enable HW acceleration are installed from this source [https://github.com/intel/media-driver](url).

**Comment by Zabrimus** [comment]
Did you install one of the vaapi vdpau wrapper?
```
Besitzer von NVidia-Karten
Sinnvoll ist auf jeden Fall einen Wrapper vaapi -> vdpau installieren. Gefunden habe diese hier
https://gitlab.com/aar642/libva-vdpau-driver und https://github.com/xtknight/vdpau-va-driver-vp9
```
All following parameters are availble for the browser:
Another test is to disable the GPU rendering to test if software rendering working at all - but it's slow
```
--disable-gpu
```
Further tests are possible with 
```
--use-gl=egl
--use-gl=desktop
```
Or it's possible that your GPU is blacklisted. You could try
```
--ignore-gpu-blocklist
```
You can also check if vaapi is installed. On my NVidia system i get
```
vdr-osr-browser/Release$ vainfo
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.4.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API (arekinath) - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG4Simple            : VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
      <unknown profile>               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
```

**Comment by Kitoko86** [comment]
Sorry for the delay,

Afters hours of trials and errors, it works finally. I forgot to create the hbbtv.conf file and his symlink. Thanks for your support.
